import React,{useEffect,useMemo,useState}from'react';
import{Avatar,Card,Col,Empty,Row,Space,Tag,Typography,message}from'antd';
import{CustomerServiceOutlined,MailOutlined,PhoneOutlined,TeamOutlined}from'@ant-design/icons';
import userApi from'../../api/userApi';
const{Title,Text}=Typography;const ROLES=['Bí thư','Phó bí thư','Chi ủy viên'];
const ContactPage=()=>{const[contact,setContact]=useState({dau_moi:[]});useEffect(()=>{userApi.getBranchContact().then(r=>setContact(r.data||{dau_moi:[]})).catch(e=>message.error(e.response?.data?.message||'Lỗi tải danh bạ Chi ủy'));},[]);const sorted=useMemo(()=>[...(contact.dau_moi||[])].sort((a,b)=>ROLES.indexOf(a.chuc_vu)-ROLES.indexOf(b.chuc_vu)),[contact.dau_moi]);return<div>
  <div style={{background:'linear-gradient(135deg,#8f151a,#b52328)',borderRadius:18,padding:'24px 28px',color:'#fff',marginBottom:22}}><Title level={2} style={{color:'#fff',margin:0}}><CustomerServiceOutlined/> Liên hệ Chi ủy</Title><Text style={{color:'rgba(255,255,255,.82)'}}>Danh bạ Chi ủy của {contact.ten_chi_bo||'Chi bộ'}</Text></div>
  <Card title={<Space><TeamOutlined/>Chi ủy {contact.ten_chi_bo||''}</Space>} style={{maxWidth:980,margin:'0 auto'}}>{sorted.length?<Row gutter={[16,16]}>{sorted.map((x,index)=><Col xs={24} md={12} lg={x.chuc_vu==='Bí thư'?24:12} key={`${x.chuc_vu}-${index}`}><Card size="small" style={{height:'100%',background:x.chuc_vu==='Bí thư'?'#fffaf0':'#fff'}}><Space align="start" size={14}><Avatar shape="square" size={52} style={{background:'#a91f23'}}>{x.ho_ten?.[0]||'C'}</Avatar><div><Tag color={x.chuc_vu==='Bí thư'?'red':x.chuc_vu==='Phó bí thư'?'gold':'blue'}>{x.chuc_vu||'Chi ủy viên'}</Tag><Title level={5} style={{margin:'7px 0'}}>{x.ho_ten}</Title><Space direction="vertical" size={3}>{x.so_dien_thoai&&<a href={`tel:${x.so_dien_thoai}`}><PhoneOutlined/> {x.so_dien_thoai}</a>}{x.email&&<a href={`mailto:${x.email}`}><MailOutlined/> {x.email}</a>}</Space></div></Space></Card></Col>)}</Row>:<Empty description="Chi ủy chưa cập nhật danh bạ"/>}</Card>
</div>};export default ContactPage;
