import React, { useEffect, useState } from 'react';
import { Button, Card, Descriptions, Drawer, Empty, Form, Input, List, Select, Space, Switch, Table, Tabs, Tag, message } from 'antd';
import { CustomerServiceOutlined, MailOutlined, MessageOutlined, PhoneOutlined, PlusOutlined, SaveOutlined, SendOutlined } from '@ant-design/icons';
import dayjs from 'dayjs';
import axios from '../services/axiosConfig';
import PageHeader from '../components/PageHeader';

const statusLabel={Moi:'Mới',Da_tiep_nhan:'Đã tiếp nhận',Dang_xu_ly:'Đang xử lý',Da_phan_hoi:'Đã phản hồi',Da_dong:'Đã đóng'};
const SupportManager=()=>{
  const [form]=Form.useForm(); const [feedback,setFeedback]=useState([]); const [thread,setThread]=useState(null); const [reply,setReply]=useState(''); const [loading,setLoading]=useState(false);
  const load=async()=>{setLoading(true);try{const [c,f]=await Promise.all([axios.get('/support/contact'),axios.get('/support/feedback')]);form.setFieldsValue({...c.data,dau_moi:c.data.dau_moi?.length?c.data.dau_moi:[{}]});setFeedback(f.data||[]);}catch(e){message.error(e.response?.data?.message||'Lỗi tải dữ liệu hỗ trợ');}finally{setLoading(false);}};
  useEffect(()=>{load();},[]); // eslint-disable-line react-hooks/exhaustive-deps
  const save=async values=>{try{await axios.put('/support/contact',values);message.success('Đã cập nhật thông tin liên hệ');load();}catch(e){message.error(e.response?.data?.message||'Lỗi cập nhật');}};
  const openThread=async id=>{try{const res=await axios.get(`/support/feedback/${id}`);setThread(res.data);}catch(e){message.error(e.response?.data?.message||'Lỗi tải góp ý');}};
  const sendReply=async()=>{if(!reply.trim())return;try{await axios.post(`/support/feedback/${thread.feedback.ma_gop_y}/replies`,{noi_dung:reply});setReply('');openThread(thread.feedback.ma_gop_y);load();}catch(e){message.error(e.response?.data?.message||'Lỗi phản hồi');}};
  const updateStatus=async value=>{try{await axios.put(`/support/feedback/${thread.feedback.ma_gop_y}/status`,{trang_thai:value});openThread(thread.feedback.ma_gop_y);load();}catch(e){message.error(e.response?.data?.message||'Lỗi cập nhật trạng thái');}};
  const columns=[{title:'Góp ý',dataIndex:'tieu_de',render:(text,row)=><div><b>{text}</b><div style={{fontSize:12,color:'#8c8c8c'}}>{row.an_danh?'Ẩn danh':row.ho_ten} · {dayjs(row.thoi_gian_tao).format('DD/MM/YYYY HH:mm')}</div></div>},{title:'Chủ đề',dataIndex:'chu_de',render:v=><Tag>{v.replaceAll('_',' ')}</Tag>},{title:'Trạng thái',dataIndex:'trang_thai',render:v=><Tag color={v==='Moi'?'red':v==='Da_dong'?'default':'blue'}>{statusLabel[v]}</Tag>},{title:'Phản hồi',dataIndex:'so_phan_hoi',align:'center'},{title:'',width:90,render:(_,row)=><Button onClick={()=>openThread(row.ma_gop_y)}>Xem</Button>}];
  return <div style={{fontFamily:'Be Vietnam Pro, sans-serif'}}><PageHeader icon={<CustomerServiceOutlined/>} title="Liên hệ & Góp ý" subtitle="Cập nhật đầu mối hỗ trợ và phản hồi ý kiến của Đảng viên"/><Card style={{borderRadius:16,boxShadow:'0 2px 16px rgba(0,0,0,.07)'}}><Tabs items={[{key:'contact',label:<Space><PhoneOutlined/>Thông tin liên hệ</Space>,children:<Form form={form} layout="vertical" onFinish={save}><Form.Item name="ten_don_vi" label="Tên đơn vị/Chi ủy"><Input/></Form.Item><Space align="start" wrap style={{width:'100%'}}><Form.Item name="so_dien_thoai" label="Số điện thoại"><Input prefix={<PhoneOutlined/>}/></Form.Item><Form.Item name="email" label="Email"><Input prefix={<MailOutlined/>}/></Form.Item><Form.Item name="gio_ho_tro" label="Giờ hỗ trợ"><Input placeholder="Thứ 2–6, 08:00–17:00"/></Form.Item></Space><Form.Item name="dia_chi" label="Địa chỉ"><Input.TextArea rows={2}/></Form.Item><Form.Item name="mo_ta" label="Thông tin hướng dẫn"><Input.TextArea rows={3}/></Form.Item><Form.List name="dau_moi">{(fields,{add,remove})=><><div style={{display:'flex',justifyContent:'space-between',marginBottom:10}}><b>Đầu mối Chi ủy</b><Button icon={<PlusOutlined/>} onClick={()=>add()}>Thêm đầu mối</Button></div>{fields.map(({key,name,...rest})=><Space key={key} align="baseline" wrap><Form.Item {...rest} name={[name,'ho_ten']} rules={[{required:true,message:'Nhập họ tên'}]}><Input placeholder="Họ tên"/></Form.Item><Form.Item {...rest} name={[name,'chuc_vu']}><Input placeholder="Chức vụ"/></Form.Item><Form.Item {...rest} name={[name,'so_dien_thoai']}><Input placeholder="Điện thoại"/></Form.Item><Form.Item {...rest} name={[name,'email']}><Input placeholder="Email"/></Form.Item><Button danger onClick={()=>remove(name)}>Xóa</Button></Space>)}</>}</Form.List><Form.Item name="cong_khai" label="Công khai cho Đảng viên" valuePropName="checked"><Switch/></Form.Item><Button type="primary" htmlType="submit" icon={<SaveOutlined/>}>Lưu thông tin</Button></Form>},{key:'feedback',label:<Space><MessageOutlined/>Hộp thư góp ý</Space>,children:<Table loading={loading} rowKey="ma_gop_y" dataSource={feedback} columns={columns} scroll={{x:700}}/>}]}/></Card>
  <Drawer title={thread?.feedback?.tieu_de} open={Boolean(thread)} onClose={()=>setThread(null)} width={620}>{thread?<><Descriptions bordered size="small" column={1}><Descriptions.Item label="Người gửi">{thread.feedback.ho_ten}</Descriptions.Item><Descriptions.Item label="Chủ đề">{thread.feedback.chu_de?.replaceAll('_',' ')}</Descriptions.Item><Descriptions.Item label="Trạng thái"><Select value={thread.feedback.trang_thai} onChange={updateStatus} style={{width:180}} options={Object.entries(statusLabel).map(([value,label])=>({value,label}))}/></Descriptions.Item><Descriptions.Item label="Nội dung">{thread.feedback.noi_dung}</Descriptions.Item></Descriptions><List style={{marginTop:20}} dataSource={thread.replies} locale={{emptyText:<Empty description="Chưa có phản hồi" image={Empty.PRESENTED_IMAGE_SIMPLE}/>}} renderItem={item=><List.Item><List.Item.Meta title={`${item.vai_tro==='Admin'?'Chi ủy':'Đảng viên'} · ${item.ho_ten}`} description={<><div style={{color:'#262626',whiteSpace:'pre-wrap'}}>{item.noi_dung}</div><small>{dayjs(item.thoi_gian_tao).format('DD/MM/YYYY HH:mm')}</small></>}/></List.Item>}/><Space.Compact style={{width:'100%'}}><Input.TextArea value={reply} onChange={e=>setReply(e.target.value)} autoSize={{minRows:2,maxRows:5}} placeholder="Nhập phản hồi..."/><Button type="primary" icon={<SendOutlined/>} onClick={sendReply}>Gửi</Button></Space.Compact></>:null}</Drawer></div>;
};
export default SupportManager;
