import React, { useEffect, useMemo, useState } from 'react';
import { Alert, Button, Card, Col, Descriptions, Drawer, Empty, Form, Input, Progress, Row, Select, Space, Tag, Typography, Upload, message } from 'antd';
import { ClockCircleOutlined, FileDoneOutlined, InboxOutlined, LinkOutlined, SendOutlined } from '@ant-design/icons';
import dayjs from 'dayjs';
import userApi from '../../api/userApi';
import RichTextEditor,{RichTextContent} from '../../components/RichTextEditor';

const { Title, Text, Paragraph }=Typography;
const statusMeta={Chua_xem:['default','Chưa xem'],Chua_nop:['warning','Chưa nộp'],Da_nop:['blue','Đã nộp'],Nop_tre:['orange','Nộp trễ'],Can_bo_sung:['volcano','Cần bổ sung'],Da_duyet:['green','Đã duyệt'],Khong_dat:['red','Không đạt']};
const TasksPage=()=>{
 const [tasks,setTasks]=useState([]);const [loading,setLoading]=useState(false);const [filter,setFilter]=useState('all');const [detail,setDetail]=useState(null);const [fileList,setFileList]=useState([]);const [submitting,setSubmitting]=useState(false);const [form]=Form.useForm();
 const load=async()=>{setLoading(true);try{const r=await userApi.getMyTasks();setTasks(r.data||[]);}catch(e){message.error(e.response?.data?.message||'Lỗi tải nhiệm vụ');}finally{setLoading(false);}};useEffect(()=>{load();},[]);
 const open=async id=>{try{const r=await userApi.getMyTask(id);setDetail(r.data);form.setFieldsValue({ket_qua:r.data.task.ket_qua,ghi_chu_dang_vien:r.data.task.ghi_chu_dang_vien});}catch(e){message.error(e.response?.data?.message||'Lỗi tải nhiệm vụ');}};
 const submit=async values=>{setSubmitting(true);try{const fd=new FormData();fileList.forEach(x=>fd.append('files',x.originFileObj));fd.append('ket_qua',values.ket_qua||'');fd.append('ghi_chu_dang_vien',values.ghi_chu_dang_vien||'');await userApi.submitTaskEvidence(detail.task.ma_nguoi_nhan,fd);message.success('Đã nộp minh chứng');setFileList([]);await open(detail.task.ma_nhiem_vu);load();}catch(e){message.error(e.response?.data?.message||'Lỗi nộp minh chứng');}finally{setSubmitting(false);}};
 const visible=useMemo(()=>tasks.filter(x=>filter==='all'||x.trang_thai_nop===filter),[tasks,filter]);const completed=tasks.filter(x=>x.trang_thai_nop==='Da_duyet').length;
 return <div><div style={{background:'linear-gradient(135deg,#8f151a,#b52328)',borderRadius:18,padding:'24px 28px',color:'#fff',marginBottom:22}}><Title level={2} style={{color:'#fff',margin:0}}><FileDoneOutlined/> Nhiệm vụ & Minh chứng</Title><Text style={{color:'rgba(255,255,255,.82)'}}>Theo dõi nhiệm vụ được giao và nộp kết quả tập trung</Text></div>
 <Row gutter={[14,14]} style={{marginBottom:18}}><Col xs={24} md={8}><Card><Text type="secondary">Tổng nhiệm vụ</Text><Title level={3} style={{margin:0}}>{tasks.length}</Title></Card></Col><Col xs={24} md={8}><Card><Text type="secondary">Đã hoàn thành</Text><Title level={3} style={{margin:0,color:'#389e0d'}}>{completed}</Title></Card></Col><Col xs={24} md={8}><Card><Text type="secondary">Tiến độ</Text><Progress percent={tasks.length?Math.round(completed/tasks.length*100):0}/></Card></Col></Row>
 <Card><div style={{display:'flex',justifyContent:'space-between',gap:10,marginBottom:16,flexWrap:'wrap'}}><b>Danh sách nhiệm vụ của bạn</b><Select value={filter} onChange={setFilter} style={{width:170}} options={[{value:'all',label:'Tất cả trạng thái'},...Object.entries(statusMeta).map(([value,m])=>({value,label:m[1]}))]}/></div>{visible.length?<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(280px,1fr))',gap:14}}>{visible.map(item=><Card key={item.ma_nhiem_vu} hoverable onClick={()=>open(item.ma_nhiem_vu)} style={{borderTop:'3px solid #a91f23'}}><Space direction="vertical" size={8} style={{width:'100%'}}><Space style={{justifyContent:'space-between',width:'100%'}}><Tag>{item.loai_nhiem_vu?.replaceAll('_',' ')}</Tag><Tag color={statusMeta[item.trang_thai_nop]?.[0]}>{statusMeta[item.trang_thai_nop]?.[1]}</Tag></Space><Title level={5} style={{margin:0}}>{item.tieu_de}</Title><Text type="secondary"><ClockCircleOutlined/> {item.han_nop?`Hạn ${dayjs(item.han_nop).format('DD/MM/YYYY HH:mm')}`:'Không giới hạn'}</Text><Text>{item.so_minh_chung||0} minh chứng đã nộp</Text></Space></Card>)}</div>:<Empty description={loading?'Đang tải...':'Chưa có nhiệm vụ phù hợp'}/>}</Card>
 <Drawer title={detail?.task?.tieu_de} open={Boolean(detail)} onClose={()=>setDetail(null)} width={620}>{detail&&<><Descriptions bordered size="small" column={1}><Descriptions.Item label="Trạng thái"><Tag color={statusMeta[detail.task.trang_thai_nop]?.[0]}>{statusMeta[detail.task.trang_thai_nop]?.[1]}</Tag></Descriptions.Item><Descriptions.Item label="Hạn nộp">{detail.task.han_nop?dayjs(detail.task.han_nop).format('DD/MM/YYYY HH:mm'):'Không giới hạn'}</Descriptions.Item><Descriptions.Item label="Mô tả">{detail.task.mo_ta?<RichTextContent html={detail.task.mo_ta}/>:<Paragraph style={{margin:0}}>—</Paragraph>}</Descriptions.Item>{detail.task.link_huong_dan&&<Descriptions.Item label="Hướng dẫn"><a href={detail.task.link_huong_dan} target="_blank" rel="noreferrer"><LinkOutlined/> Mở tài liệu</a></Descriptions.Item>}</Descriptions>{detail.task.phan_hoi_chi_uy&&<Alert type={detail.task.trang_thai_nop==='Can_bo_sung'?'warning':'info'} showIcon message="Phản hồi của Chi ủy" description={detail.task.phan_hoi_chi_uy} style={{marginTop:16}}/>}<Card title="Minh chứng đã nộp" size="small" style={{marginTop:16}}>{detail.evidence.length?detail.evidence.map(f=><div key={f.ma_minh_chung}><a href={f.file_url} target="_blank" rel="noreferrer">{f.ten_file}</a></div>):<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="Chưa có minh chứng"/>}</Card>{detail.task.trang_thai==='Dang_mo'&&!['Da_duyet','Khong_dat'].includes(detail.task.trang_thai_nop)&&<Card title="Nộp kết quả" size="small" style={{marginTop:16}}><Form form={form} layout="vertical" onFinish={submit}><Form.Item name="ket_qua" label="Kết quả/Điểm số"><Input placeholder="Ví dụ: 10/10 hoặc Đã hoàn thành"/></Form.Item><Form.Item name="ghi_chu_dang_vien" label="Ghi chú"><RichTextEditor minHeight={110}/></Form.Item><Upload.Dragger multiple maxCount={5} fileList={fileList} beforeUpload={()=>false} onChange={({fileList:list})=>setFileList(list)} accept="image/*,.pdf,.doc,.docx"><InboxOutlined style={{fontSize:34,color:'#a91f23'}}/><p>Tải tối đa 5 ảnh/PDF/tài liệu, mỗi file không quá 10MB</p></Upload.Dragger><Button type="primary" htmlType="submit" loading={submitting} icon={<SendOutlined/>} block size="large" style={{marginTop:14}}>Nộp minh chứng</Button></Form></Card>}</>}</Drawer></div>;
};
export default TasksPage;
